### ISSUE TITLE
fatal error: NvInfer.h: No such file or directory

### ISSUE THREAD

**Issue by dutxubo** [zerollzeng/tiny-tensorrt#10]
I follow the instructions
```
git clone --recurse-submodules  https://github.com/zerollzeng/tiny-tensorrt.git
cd tiny-tensorrt
mkdir build && cd build && cmake ..
```
It's OK
```
$cmake ..
-- CUDA supported archs: 60;61;70;75
-- CUDA targeted archs: 60;61;70;75
-- Generated gencode flags:  -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_75,code=sm_75 -gencode arch=compute_75,code=compute_75
-- Found TensorRT headers at /home/songbai.xb/package/TensorRT/include
-- Build python
-- pybind11 v2.3.dev1
-- Configuring done
-- Generating done
-- Build files have been written to: /home/songbai.xb/package/tiny-tensorrt/build
```
But when I run `make`, i got the error
```
$make
[ 10%] Building NVCC (Device) object CMakeFiles/tinytrt.dir/plugin/YoloLayerPlugin/tinytrt_generated_YoloLayerPlugin.cu.o
In file included from /home/songbai.xb/package/tiny-tensorrt/plugin/YoloLayerPlugin/YoloLayerPlugin.cu:1:0:
/home/songbai.xb/package/tiny-tensorrt/plugin/YoloLayerPlugin/YoloLayerPlugin.hpp:17:21: fatal error: NvInfer.h: No such file or directory
compilation terminated.
CMake Error at tinytrt_generated_YoloLayerPlugin.cu.o.cmake:219 (message):
  Error generating
  /home/songbai.xb/package/tiny-tensorrt/build/CMakeFiles/tinytrt.dir/plugin/YoloLayerPlugin/./tinytrt_generated_YoloLayerPlugin.cu.o


make[2]: *** [CMakeFiles/tinytrt.dir/plugin/YoloLayerPlugin/tinytrt_generated_YoloLayerPlugin.cu.o] Error 1
make[1]: *** [CMakeFiles/tinytrt.dir/all] Error 2
make: *** [all] Error 2
```
My environment configuration:
- Red Hat 4.8.5-4
- TensorRT version 7
- Python version 3.6

Sorry, this seems like a low-level question. But I am not familiar with linux and tensorrt.

**Comment by zerollzeng** [comment]
according to your description, I think that's because your TensorRT didn't install to /usr/lib, so it can not find NvInfer.h. try to add
`include_directories(/home/songbai.xb/package/TensorRT/include)`
under this line
https://github.com/zerollzeng/tiny-tensorrt/blob/d3c8a5972be30e9d6d4f43c7391fc2920f6f8f10/CMakeLists.txt#L34
and see if it helps :)

**Comment by dutxubo** [comment]
yes, thank you. I solved the above problem according to your instructions. But a new problem has arisen.
```
[100%] Linking CXX shared library pytrt.cpython-36m-x86_64-linux-gnu.so
/usr/bin/ld: cannot find -lnvinfer
/usr/bin/ld: cannot find -lnvinfer_plugin
/usr/bin/ld: cannot find -lnvparsers
/usr/bin/ld: cannot find -lnvonnxparser
/usr/bin/ld: cannot find -lnvcaffe_parser
collect2: error: ld returned 1 exit status
make[2]: *** [pytrt.cpython-36m-x86_64-linux-gnu.so] Error 1
make[1]: *** [CMakeFiles/pytrt.dir/all] Error 2
make: *** [all] Error 2
```
I guess it's still the path that's causing the problem. How can I change the link path? And I am not a root user. 
Thanks again for your feedback

**Comment by zerollzeng** [comment]
try add
`link_directories(/home/songbai.xb/package/TensorRT/lib)`
in CMakeLists.txt, I am not very sure about the path, but it should be libraries like libnvinfer.so located.

**Comment by dutxubo** [comment]
Yes, thank you very much. I should learn more about cmake.
I will close this problem. Thank you!

**Comment by zerollzeng** [comment]
you are welcome, you can take a look at [tensorrt-zoo](https://github.com/zerollzeng/tensorrt-zoo), it has some good examples about how to use tiny-tensorrt.
