### ISSUE TITLE
tensorrt7 batch infer exception

### ISSUE THREAD

**Issue by dtiny** [zerollzeng/tiny-tensorrt#14]
please descript your problem in **English** if possible. it will to helpful to more people
**Describe the bug**

**To Reproduce**
1. I use your code correctly in one image infer. When I change one image to batch images, only first image result was correct and the rest results were 0. Did I use code in wrong ways?  Were you test code with batch infer?
Here is my batch test code.

//main function for preprocess image. batch test in TestBatchForward function
Trt trt;
int batch = 3;
trt.CreateCaffeEngine(prototxt, caffe_model, engine_file, output_blob_name, batch, 0, 0);
Mat input = cv::imread("images/1.jpg");
cv::Mat processed_img;
processed_img.convertTo(input , CV_32FC3);
processed_img = processed_img / 128.0;
std::vector<float>mInputBuf;
float * mInputBuf_arr = new float[batch * trt.mInputSize];
float ** mOutputBuf_arr = new float*[trt.mOutputNum];
for (int i = 0; i < trt.mOutputNum; ++i){
        mOutputBuf_arr[i] = new float[batch * trt.mOutputSizes[i]];
    }
    int img_h = processed_img.rows, img_w = processed_img.cols;
    for (int i = 0 ; i < batch; ++i)
    {
       for (int h = 0; h < img_h; ++h)
        {
            for (int w = 0; w < img_w; ++w)
            {
                cv::Vec3f intensity = processed_img.at<cv::Vec3f>(h, w);
                for (int c = 0; c < 3; ++c){
                    mInputBuf_arr[i * 3 * img_h * img_w + c * img_h * img_w + h * img_w + w] = intensity.val[c];
                }
            }
        }
    }
    trt.TestForward(mInputBuf_arr, mOutputBuf_arr, batch );

//test batch infer function
void Trt::TestBatchForward(float *input, float **outputs, int batchSize){
    void **buffers = new void*[1 + mOutputNum];
    int inputByteSize = batchSize * mInputSize * sizeof(float);
    vector<int> outputByteSizes(mOutputNum);
    for (int i = 0; i < mOutputNum; ++i){
        outputByteSizes[i] = batchSize * mOutputSizes[i] * sizeof(float);
    }
    // create GPU buffers and a stream
    buffers[mInputIdx] = safeCudaMalloc(inputByteSize);
    for (int i = 0; i < mOutputNum; ++i){
        buffers[mOutputIdx[i]] = safeCudaMalloc(outputByteSizes[i]);
    }
    cudaStream_t stream;
    cudaStreamCreate(&stream);
    // DMA the input to the GPU, execute the batch asynchronously, and DMA it back:
    CUDA_CHECK(cudaMemcpyAsync(buffers[mInputIdx], input, inputByteSize, cudaMemcpyHostToDevice));
    mContext->enqueueV2(buffers, stream, nullptr);
    for (int i = 0; i < mOutputNum; ++i){   
        CUDA_CHECK(cudaMemcpyAsync(outputs[i], buffers[mOutputIdx[i]], outputByteSizes[i], cudaMemcpyDeviceToHost, stream));       
    }

    cudaStreamSynchronize(stream);
//print infer results
    for(int i = 0; i< outputByteSizes[0]/sizeof(float); ++i){
        std::cout<<" "<<outputs[0][i];
    }
    // release the stream and the buffers
    cudaStreamDestroy(stream);
    cudaFree(buffers[mInputIdx]);
    for (int i = 0; i < mOutputNum; ++i)
        cudaFree(buffers[mOutputIdx[i]]);
    delete buffers;
}

// print batch infer results
 0.418353 -0.339835 1.47774 0.465297 0.0953144 1.4845 -0.868854 1.39476 0.25819 -0.0994663 0.669871 0.411211 -0.000274749 0.445082 0.383733 0.674614 0.0163638 -0.952645 -0.157516 -0.827935 -1.05047 0.0927525 -0.0534809 -1.23247 -0.493299 -0.594926 0.176294 0.895567 0.936891 -0.543378 -0.469052 0.0572796 -1.17963 1.65981 -0.208103 -0.996869 -0.0920075 0.884695 0.987625 -0.248668 0.523404 0.144057 -0.64876 1.04438 -0.824669 -0.720045 1.81286 0.0510059 -0.868279 0.252882 1.50966 -0.674424 -0.0196954 0.425617 -0.0287924 -0.52397 -0.725012 0.0798434 -1.3974 0.751449 0.301873 -1.94457 0.167489 -0.780992 0.564487 -1.12608 0.24968 0.0377088 -0.0867874 -0.719365 0.512193 0.301276 -1.97736 0.564605 0.0911436 0.228572 -1.05391 0.282327 0.739067 -1.9737 0.49959 -1.01108 -0.162155 -0.600142 -0.0336548 -0.535204 0.231381 -0.245688 -0.569683 -0.942794 -1.8423 -0.123207 -0.185064 1.11275 0.967386 -0.828103 0.378194 -0.0876856 -0.206545 0.0262256 -0.922973 -2.0892 -0.0316179 1.35116 -0.52758 -1.32669 -0.427484 -1.17367 -1.23769 0.276887 2.15691 -0.229757 0.499061 -0.888753 -1.46438 -0.443409 1.40631 -0.337232 0.107081 -0.00940938 0.426785 0.272116 -1.51604 -0.42896 -0.154142 -1.19746 -0.489736 0.979325 -1.02163 0.224278 -0.985483 -1.12177 0.100808 0.146919 0.54694 -1.22898 0.965479 -1.68386 -0.965069 -3.18732 0.0472699 0.851204 0.286965 -1.72552 0.0656358 -0.448506 -0.0913214 0.278511 0.372425 -1.30757 1.63169 -0.301794 1.15513 0.501574 -0.530693 -1.20217 0.131365 -0.197304 -0.322259 -0.572622 0.752584 -1.19785 -0.296245 -0.416246 -1.4171 -0.71049 -0.395232 -0.48165 -0.507815 -1.29982 1.01059 0.0593524 0.851655 -1.88254 -1.62513 -1.72685 0.547141 0.573632 0.436763 0.914935 -0.149617 -0.371168 1.3088 -0.602601 -2.2409 -0.476194 -0.709228 -0.569816 0.655495 0.611702 0.624206 -1.53138 -0.288514 -0.119794 -0.228668 1.03963 -0.381374 -0.666507 -0.619535 -0.811937 -0.412612 0.431372 -1.72768 -1.0153 -0.0149388 -0.618793 1.29511 -1.11848 1.12527 -0.346998 -2.08662 -0.486109 0.731461 0.149961 -0.384163 0.33348 0.170461 -1.34745 0.795712 -0.065213 0.992072 -0.353411 -1.34885 -0.524941 2.24559 0.222608 0.819619 0.775753 -0.900504 0.412701 0.647769 -0.305382 -0.239375 1.72451 -1.58867 0.661653 -0.616319 -0.71326 -0.171345 1.19174 -0.165266 0.2055 0.239568 -1.09009 0.623425 -0.278796 1.26333 -1.27333 0.297172 0.409337 0.86182 -0.225835 -0.595393 1.01205 0.288939 -0.390605 1.44718 0.859836 0.532982 0.855148 0.458101 0.590636 1.17607 0.76743 -1.91153 -0.415302 0.336386 0.819023 0.706001 0.598343 -0.471056 0.310444 -0.751837 -0.935275 0.242999 1.89957 -0.121657 -0.669892 -0.224158 0.134661 0.339971 1.05574 0.427598 1.77567 -0.0999954 0.490235 1.92501 0.820809 0.136698 -0.509513 0.0305831 -1.10454 -0.660873 -0.554326 -1.33539 -0.179265 -0.145002 0.409617 -1.45366 -0.927122 1.27614 -1.28289 -0.203767 -0.0649702 0.187397 0.134719 -0.385763 0.177142 -0.8878 -0.719888 0.266835 0.420066 -1.10512 0.982305 1.21624 -1.03413 0.655194 -0.796016 -1.0781 0.588296 -0.0244052 0.291401 -0.620948 0.541094 0.188643 -0.241535 0.623881 -0.834549 -1.41047 0.599246 -0.330083 0.436397 -0.194659 -0.898143 1.36357 -0.647773 1.68338 0.732466 -0.864251 1.84152 -0.3384 1.11318 1.9019 0.162629 0.363904 0.335144 0.514491 -1.61566 0.767211 -0.117496 -0.402927 0.655741 -0.313098 -0.635456 0.390261 -1.58337 0.542587 -0.573682 0.0339768 0.059598 0.788912 1.1274 -0.0388548 -1.05345 -0.361318 -1.00671 0.320392 0.578829 -0.525593 0.477257 0.298906 -1.05488 -1.07125 -1.08544 -0.141793 -1.92073 0.710626 0.390971 0.20998 1.47727 1.02344 0.317808 0.08342 0.453745 1.63591 -0.385809 1.43089 -1.67335 0.0755103 -1.44526 1.62198 -1.75994 0.272815 -0.402808 -1.14742 0.486125 -0.0525881 1.71581 0.622237 -1.37216 1.32343 -0.666142 0.659396 -0.947226 -0.835725 -0.12258 -0.35864 -1.19002 -0.173705 1.1276 -2.11634 -1.57015 0.723291 -0.624017 -0.920398 2.06936 -0.0922877 -1.47185 0.183379 0.928974 1.01896 -1.52692 -0.643599 0.609246 -0.853222 -0.0295406 -0.512175 -0.592418 -0.320688 -0.503442 -0.339471 -1.19084 0.540145 0.457263 0.600148 -0.609822 1.14102 0.945529 0.365958 1.20306 -0.608461 0.559578 1.09058 1.15598 1.30303 -0.186021 -1.03349 -2.47128 0.331959 -0.0917509 -0.935688 0.319987 -0.667024 0.524795 -0.437112 1.16005 -0.105717 0.0594055 1.30721 -0.695715 -0.544471 0.644166 -0.155529 -0.413081 0.974383 -0.0977418 -1.20436 1.71986 0.285367 -0.0992153 -0.165331 0.251895 0.327887 -1.12094 -0.962676 -1.03678 -0.114288 -0.348816 1.81246 1.09397 0.800078 1.98242 -0.86003 0.189152 -1.00618 -1.32627 -1.15713 1.73325 0.113342 0.861359 0.269333 -0.149267 0.17613 1.39301 -0.147052 -0.707363 1.50977 -0.476737 0.461255 1.03155 -0.442583 0.804075 -0.414472 -0.807355 0.553154 -1.75598 -0.0251481 -0.194252 1.23312 1.07619 -1.44525 0.627838 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

**Expected behavior**

**Screenshots**

**System environment (please complete the following information):**
 - OS: ubuntu16.04
 - TensorRT version:7.x
 - Graphic card:GPU 1080ti
 - Others:

**Additional context**

**Comment by zerollzeng** [comment]
the code has not indent and it's hard to read, can you edit with correct markdown syntax?

**Comment by zerollzeng** [comment]
if you are not familiar with markdown syntax you can a look at this [link](https://github.com/microsoft/vscode/issues/36069)

**Comment by zerollzeng** [comment]
close due to inactivity
