### ISSUE TITLE
batch inference demo

### ISSUE THREAD

**Issue by xiexuliunian** [zerollzeng/tiny-tensorrt#18]
Nice work! I have use this repo for about one month,It is really easy to use and easy to understand.Up Up now days I want to use this repo for batch inference ,Can you tell me how to do it? or provide a batch inference demo? sincerely hope for you,Thanks a lot

**Comment by zerollzeng** [comment]
Just set the maxBatchSize and inference with multiple batch should works, although I didn't test yet

**Comment by xiexuliunian** [comment]
yeah,I know should to change MaxBatchSize,I have problem at how to change the 
![image](https://user-images.githubusercontent.com/24749356/80573800-41324480-8a33-11ea-8202-eeb04bcf46d2.png)
input and output into batch?

**Comment by zerollzeng** [comment]
for input you concatenate every input image to a 1d vector, like image_1 : image_2 : image_3, then your output will be output_1 : output_2 :output_3. at last you get box, landmark, and conf from output_1 for image_1.

**Comment by zerollzeng** [comment]
does your model has fix output size? eg, does box has fix size? if so you can get box_for_image_1, box_for_image_2... from box, just split the box equally?

**Comment by xiexuliunian** [comment]
yeah they all have fix size .eg for every input pic the box is 189000x4,I 'm not clear how to make the input pic in batch.......

**Comment by zerollzeng** [comment]
just concatenate them into vector like image_1 : image_2 : image_3

**Comment by xiexuliunian** [comment]
ok，I will try it .Thanks .

**Comment by zerollzeng** [comment]
close due to inactivity
