### ISSUE TITLE
你好 ，我这里报权重个数对应不上

### ISSUE THREAD

**Issue by tianyu06030020** [zerollzeng/tiny-tensorrt#19]
![image](https://user-images.githubusercontent.com/9124519/81543407-9a419700-93a8-11ea-9534-a1e84aab9222.png)

你好，我的原始模型是mxnet， 转换成了caffe模型之后再用tensorrt解析的时候caffeparser报错，但是我测试mxnet和caffe模型，结果是一致的。

prototxt文件如下：

[face_recognize.txt](https://github.com/zerollzeng/tiny-tensorrt/files/4608589/face_recognize.txt)

**Comment by tianyu06030020** [comment]
> ![image](https://user-images.githubusercontent.com/9124519/81543407-9a419700-93a8-11ea-9534-a1e84aab9222.png)
> 
> 你好，我的原始模型是mxnet， 转换成了caffe模型之后再用tensorrt解析的时候caffeparser报错，但是我测试mxnet和caffe模型，结果是一致的。
> 
> prototxt文件如下：
> 
> [face_recognize.txt](https://github.com/zerollzeng/tiny-tensorrt/files/4608589/face_recognize.txt)

@zerollzeng 解决了，注册的时候prelu层的名字没找到

**Comment by xiexuliunian** [comment]
please I want to know how do you solved this problem.......
