### ISSUE TITLE
About Custom Plugin Loading into TensorRT

### ISSUE THREAD

**Issue by StevenDCK** [zerollzeng/tiny-tensorrt#2]
can Custom Plugin compiled to .so File be loaded into TensorRT and working ? Have you done like that before?

**Comment by zerollzeng** [comment]
yes, custom plugin will loaded into .so file, so you just need to compile an .so file and use it, no need custom plugin source code.

**Comment by StevenDCK** [comment]
It would be appreciated if you post some small demos out.

**Comment by StevenDCK** [comment]
I mean use trtexec or LD_PRELOAD=libtrtcustom.so way

**Comment by zerollzeng** [comment]
you can refer to [tensorrt-zoo](https://github.com/zerollzeng/tensorrt-zoo), yolov3 sample is easy to understand

**Comment by zerollzeng** [comment]
maybe I don't really understand your problem clearly, can you state it more specific?

**Comment by StevenDCK** [comment]
Thanks!
PRELUKernel.cu		
PRELUKernel.cuh		
PRELUPlugin.cpp		
PRELUPlugin.hpp
I am trying to compile these files into .so file and hope it can work.

**Comment by zerollzeng** [comment]
you're welcome and thanks for your feedback :D
