### ISSUE TITLE
/usr/bin/ld: 找不到 -lnvinfer

### ISSUE THREAD

**Issue by JachinMa** [zerollzeng/tiny-tensorrt#20]
I was trying to install tiny-tensorrt as described in readme,but faced this problem:

/usr/bin/ld: 找不到 -lnvinfer
/usr/bin/ld: 找不到 -lnvinfer_plugin
/usr/bin/ld: 找不到 -lnvparsers
/usr/bin/ld: 找不到 -lnvonnxparser
/usr/bin/ld: 找不到 -lnvcaffe_parser
collect2: error: ld returned 1 exit status
CMakeFiles/pytrt.dir/build.make:97: recipe for target 'pytrt.cpython-37m-x86_64-linux-gnu.so' failed
make[2]: *** [pytrt.cpython-37m-x86_64-linux-gnu.so] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/pytrt.dir/all' failed
make[1]: *** [CMakeFiles/pytrt.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

I have searched it,and tried several methods,but thet didnt work.

Is there anyone could help me with this issue,thx very much.

**Comment by zerollzeng** [comment]
Did you install TensorRT correctly? and btw can you post your environment information？

**Comment by zerollzeng** [comment]
If install TensorRT correctly, take a look at issue #10

**Comment by JachinMa** [comment]
> If install TensorRT correctly, take a look at issue #10

very thx for your kind help,I successfully install tiny-tensorrt.

then I read the guide,it writes:

sys.path.append("path/to/where_pytrt.so_located/")

I dont know what this file is,I cant find it in my computer or website,could you tell me how to get this file?

should I download something?

thx again

**Comment by zerollzeng** [comment]
if you run cmake .. in tiny-tensorrt/build, them the so was in build folder

**Comment by JachinMa** [comment]
> if you run cmake .. in tiny-tensorrt/build, them the so was in build folder

thx for reply.

is it the file 'libtinytrt.so'?

I've tried 'sys.path.append("/home/mjx/tiny-tensorrt/build/")' and 'sys.path.append("/home/mjx/tiny-tensorrt/build/libtinytrt.so") but still got 'no module named 'pytrt'.'

what should I do?

**Comment by zerollzeng** [comment]
> is it the file 'libtinytrt.so'?

No, it should you should found libtinytrt.so(this is for c++ inference), and pytrt.cpython-36m-x86_64-linux-gnu.so(or other something like this) or pytrt.so for python inference, you should append this so file in your python script, and again, make sure you set BUILD_PYTHON ON, see
https://github.com/zerollzeng/tiny-tensorrt/blob/eb0d3a7a7ed7e8894f8b897cef6bada64e736331/CMakeLists.txt#L9

also take a look at my other repo tensorrt-zoo, it should be helpful to you

**Comment by JachinMa** [comment]
> > is it the file 'libtinytrt.so'?
> 
> No, it should you should found libtinytrt.so(this is for c++ inference), and pytrt.cpython-36m-x86_64-linux-gnu.so(or other something like this) or pytrt.so for python inference, you should append this so file in your python script, and again, make sure you set BUILD_PYTHON ON, see
> https://github.com/zerollzeng/tiny-tensorrt/blob/eb0d3a7a7ed7e8894f8b897cef6bada64e736331/CMakeLists.txt#L9
> 
> also take a look at my other repo tensorrt-zoo, it should be helpful to you

thx for your reply

I check the BUILD_PYTHON and its on.

so I tried re-build it,and this time I see 'pytrt.cpython-37m-x86_64-linux-gnu.so' in my build folder.

but I cant import pytrt:

'ModuleNotFoundError: No module named 'pytrt''

I've add 'sys.path.append("/home/mjx/tiny-tensorrt/build/")' and '/home/mjx/tiny-tensorrt/build/' to my PATH and PYTHON via vim bashrc file.

and I checked the tensorrt-zoo,there is nobody who faced my problem.

so...what should I do?

these information may be helpful:my system is ubuntu 18.04,gpu is 2080ti.cuda version=10.2,python=3.6.

**Comment by zerollzeng** [comment]
That is weird
![image](https://user-images.githubusercontent.com/38289304/82197467-a3dd7880-992d-11ea-9ebd-19ac53c04b8b.png)

**Comment by zerollzeng** [comment]
oh I know, the version of python of pytrt.cpython-37m-x86_64-linux-gnu.so if different, you build this so in python 3.7, so you can't import it in python 3.6

**Comment by JachinMa** [comment]
> oh I know, the version of python of pytrt.cpython-37m-x86_64-linux-gnu.so is different, you build this so in python 3.7, so you can't import it in python 3.6

that make sense.

I have a default anaconda environment which is 3.7 .But my work virtual anaconda environment is 3.6.So I guess when I do make command,it use the default python,even though I was in virtual environment.

So I think I should reinstall my anaconda,and it should soon work well.

**Comment by zerollzeng** [comment]
Did you solve  your problem yet? if so, please close the issue :D

**Comment by zerollzeng** [comment]
close due to inactivity
