### ISSUE TITLE
plugin on my own project

### ISSUE THREAD

**Issue by xiexuliunian** [zerollzeng/tiny-tensorrt#22]
In some project I can't use tiny-tensorrt,But I really need the prelu plugin in my preject ,so I copy some of your prelu plugin code in my code ,but it occures some error blow
![image](https://user-images.githubusercontent.com/24749356/83217518-8c5c8600-a19e-11ea-9663-0c539d82b921.png)
Can you give some advices on not use tiny-tensorrt but need for prelu plugin in my ow project?

**Comment by zerollzeng** [comment]
that means your device does not support fp16, just delete the fp16 part in prelu plugin. can you post your environment?

**Comment by zerollzeng** [comment]
comment
https://github.com/zerollzeng/tiny-tensorrt/blob/fbc8a549cb0620b3310f0e1a990cb14af85f3e5e/plugin/PReLUPlugin/PReLUPlugin.cu#L185-L192
should works,

**Comment by xiexuliunian** [comment]
OK,I will have a try.the enviroment I will later post on.go lunch。

**Comment by xiexuliunian** [comment]
Environment:

- software:
cuda:10.0
cudnn:7.6.5
TensorRT:7.0.1

- hardware:
Tesla P40

Yeah,tested。the problem solved。I will test the project result .Want to invite you to drink coffee again！！！

**Comment by zerollzeng** [comment]
LOL it's not a big deal, just keep the money for the upcoming weekend :satisfied::satisfied::satisfied:

**Comment by zerollzeng** [comment]
> comment
> https://github.com/zerollzeng/tiny-tensorrt/blob/fbc8a549cb0620b3310f0e1a990cb14af85f3e5e/plugin/PReLUPlugin/PReLUPlugin.cu#L185-L192
> 
> 
> should works,
