### ISSUE TITLE
阅读代码时的疑惑

### ISSUE THREAD

**Issue by zjd1988** [zerollzeng/tiny-tensorrt#23]
目前在看Trt.cpp代码，其中
![企业微信截图_15917583214978](https://user-images.githubusercontent.com/7134030/84222507-560df780-ab0a-11ea-8001-e03bc163355e.png)
看了下nvidia的官方api介绍，感觉这个不应该入参指定为空指针吧，只需要定义一个int变量传给，并将这个变量地址传给cudaGetDevice即可吧，目前没有GPU环境，等有空测试下。
![企业微信截图_1591758401154](https://user-images.githubusercontent.com/7134030/84222570-80f84b80-ab0a-11ea-97e2-59f5a5e00c53.png)

**Comment by zerollzeng** [comment]
Oh you are right! thanks for pointing my error @zjd1988 , I will fix it soon :smiley::smiley::smiley:

**Comment by zerollzeng** [comment]
`
#include <iostream>
#include "cuda_runtime.h"

int main() {
    // int* device = NULL; // fail
    int device = -1;
    cudaGetDevice(&device);
    if(device != -1) {
        std::cout << "succees get device: " << device  << std::endl;
    } else {
        std::cout << "fail" << std::endl;
    }
    return 0;
}

`
reproduce code btw

**Comment by zjd1988** [comment]
@zerollzeng  Thanks for your reply!!!!smiley
