### ISSUE TITLE
use wrong operator in ../tiny-tensorrt/plugin/PReLUPlugin/PReLUPlugin.cu

### ISSUE THREAD

**Issue by zjd1988** [zerollzeng/tiny-tensorrt#24]
using logical operator instead of  bit operator below code snippet
![企业微信截图_15917725923577](https://user-images.githubusercontent.com/7134030/84237702-6df67300-ab2c-11ea-9789-ecb6b84ce3ab.png)

**Comment by zerollzeng** [comment]
Haha thanks for review my code~ if you have other problem just comment under this issue to avoid issue duplication.
Best regard.

**Comment by zjd1988** [comment]
@zerollzeng Ok, thanks for your work.
