### ISSUE TITLE
Compile error----spdlog/fmt/bundled/core.h

### ISSUE THREAD

**Issue by Devincool** [zerollzeng/tiny-tensorrt#25]
please descript your problem in **English** if possible. it will to helpful to more people
**Describe the bug**
Compile ENV:
OS: win10
TensorRT: 6.0
GraphCard: RTX2060
IDE: VS2015
When I try to compile tiny-tensorRT, I got error in core.h(the path is spdlog/fmt/bundled/core.h). And the error printed is messy code. Just like the pic below:
![image](https://user-images.githubusercontent.com/6264196/85370945-19a6b680-b562-11ea-9351-4151aa28d5b9.png)

**To Reproduce**
1. use Cmake to generate VS2015  x64 project 
2. open VS2015 and push "RUN"

**Comment by Devincool** [comment]
The problem solved by changing the IDE to VS2019

**Comment by zerollzeng** [comment]
hi @Devincool  I never test tiny-tensorrt on win10, can you briefly describe how you solve the problem and  make it run on win10? It would be very helpful to those people who want to port this project to windows, thanks a lot.

**Comment by Devincool** [comment]
ok. But it still has some problem when invoking.
My modification will be committed soon.

**Comment by zerollzeng** [comment]
ok thanks for your contribution

**Comment by asherp7** [comment]
I'm having trouble with running on windows 10:
The cmake is working but when trying to run the solution I get:
"invalid numeric argument Wno-deprecated"
![image](https://user-images.githubusercontent.com/34067850/174641451-45333176-d691-4f0f-b809-ec242f165b12.png)
Any solutions?
