### ISSUE TITLE
how to know the name of the trt(trt.GetOutput()) output.

### ISSUE THREAD

**Issue by huangzhenjie** [zerollzeng/tiny-tensorrt#27]
I'm a little confused that how to know the name of the trt(trt.GetOutput()) output.
thanks

**Comment by zerollzeng** [comment]
for caffe you can find it in prototxt, and for onnx or tf, you may find it with tools like https://lutzroeder.github.io/netron/

**Comment by zerollzeng** [comment]
that's because for caffe you must specify the output name, but for onnx you don't need to specify it.

**Comment by zerollzeng** [comment]
unless you want to specify your output for some reason

**Comment by huangzhenjie** [comment]
Problem solved，thank you very much.
