### ISSUE TITLE
what about configureWithFormat?

### ISSUE THREAD

**Issue by beizhengren** [zerollzeng/tiny-tensorrt#29]
Hi @zerollzeng ,
I have not found comment about configureWithFormat.
What's configureWithFormat meaning? And how to use it?
Thank you!

**Comment by zerollzeng** [comment]
https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_plugin_v2.html#a1cdcb075b35bd92bbae33e3958098e6b

**Comment by beizhengren** [comment]
@zerollzeng Thanks.
