### ISSUE TITLE
CMake Error at CMakeLists.txt .

### ISSUE THREAD

**Issue by chaipangpang** [zerollzeng/tiny-tensorrt#3]
Thanks for your great work.
I got some errors when 'cmake ..' :
CMake Error at CMakeLists.txt:48 (pybind11_add_module):
  Unknown CMake command "pybind11_add_module".
Do u have any ads?
Thanks!

**Comment by zerollzeng** [comment]
I use pybind11 to create python api, perhaps you didn't clone the pybind11 submodule, try
`
git submodule update --init --recursive
`

**Comment by zerollzeng** [comment]
oh I forget commemt some gpu information in CMakelists.txt
`
find_package(CUDA REQUIRED)
set(
    CUDA_NVCC_FLAGS
    ${CUDA_NVCC_FLAGS};
    -O2
    # -arch=sm_50 
    # -gencode=arch=compute_50,code=sm_50 
    # -gencode=arch=compute_52,code=sm_52 
    # -gencode=arch=compute_60,code=sm_60 
    # -gencode=arch=compute_61,code=sm_61 
    # -gencode=arch=compute_70,code=sm_70 
    # -gencode=arch=compute_75,code=sm_75
    # -gencode=arch=compute_75,code=compute_75 
)
`
note difference in here, I update readme and CMakelists.txt,  you can pull newest commit.
