### ISSUE TITLE
在windows上安装不成功

### ISSUE THREAD

**Issue by duoduo1018** [zerollzeng/tiny-tensorrt#30]
您好， 想在windows上使用这个项目， 但一直安装不成功。  有没有详细的windows安装教程呢？  在win10上执行 https://github.com/Devincool/tiny-tensorrt项目，也没有成功

**Comment by zerollzeng** [comment]
抱歉这个我无法帮到你～我只熟悉linux平台

**Comment by duoduo1018** [comment]
在win10上，成功运行了，非常感谢您的分享 ！

**Comment by zerollzeng** [comment]
awesome！请问可以再简单分享一下你的做法吗？其他人可能也会遇到这个问题, 但是我不熟悉windows平台， 所以你的经验对其他需要在windows上运行tiny-tensorrt的朋友非常有帮助

**Comment by PengSunChina** [comment]
make 不成功

**Comment by sanwz** [comment]
> 在win10上，成功运行了，非常感谢您的分享 ！

请问您能方便分享一下您的解决方案吗？谢谢

**Comment by duoduo1018** [comment]
我用的是https://github.com/Devincool/tiny-tensorrt项目代码， 
电脑环境
win10,
cuda10.0
TensorRT-7.0.0.11
vs2019（vs2017/2015生成失败）
GeForce GTX 1650super
opencv 342 

把CMakeLists.txt  里面关于linux的语句注释掉， 删除 -Wfloat-conversion，这样应该就可以了
