### ISSUE TITLE
cmake  有什么要注意的地方吗

### ISSUE THREAD

**Issue by PengSunChina** [zerollzeng/tiny-tensorrt#31]
please descript your problem in **English** if possible. it will to helpful to more people
**Describe the bug**

**To Reproduce**
1. 
2. 

**Expected behavior**

**Screenshots**

**System environment (please complete the following information):**
 - OS: 
 - TensorRT version:
 - Graphic card:
 - Others:

**Additional context**

**Comment by zerollzeng** [comment]
describe your problem more clearly please :)
