### ISSUE TITLE
问一些额外的问题

### ISSUE THREAD

**Issue by xusk** [zerollzeng/tiny-tensorrt#33]
我在 tiny-tensorrt 的基础上 加入了 动态输入的方式

void Trt::ForwardAsync(nvinfer1::Dims &dim) {

    spdlog::info("start takes");
    cudaEvent_t start, stop;
    float elapsedTime;

    cudaEventCreate(&start);
    cudaEventCreate(&stop);
    cudaEventRecord(start, 0);

    //spdlog::info("set binding");
    mContext->setBindingDimensions(0, dim);
    //spdlog::info("enqueue");

//    if (!mContext->allInputDimensionsSpecified()) {
//        return -1;
//    }

    std::cout << mBinding.size() << std::endl;
    mContext->enqueueV2(mBinding.data(), stream, nullptr);
    // spdlog::info("cudaStreamSynchronize");
    cudaStreamSynchronize(stream);

    cudaEventRecord(stop, 0);
    cudaEventSynchronize(stop);
    cudaEventElapsedTime(&elapsedTime, start, stop);
    spdlog::info("net ForwardAsync takes {} ms", elapsedTime);
    //spdlog::info("ForwardAsync finish");
}
但是测试发现很慢，在我现在的场景下大概需要50ms

**Comment by zerollzeng** [comment]
你指的是dynamic shape吗?

**Comment by xusk** [comment]
> 你指的是dynamic shape吗?

是的，是不是本身dynamic shape 就会如此

**Comment by zerollzeng** [comment]
不一定,看模型,有的模型就没有影响.

**Comment by xusk** [comment]
> 不一定,看模型,有的模型就没有影响.
之前在 python api 测试   
input (1, 3, 192, 320)
start run 1000 speed test
use 1.052018404006958 trt inference time: 0.001052018404006958, fps: 950.5537129304689

但是因为python在多线程下有问题，故也尝试过   content.push() ,content.pop(); 很慢大概单次也需要50ms.

然后通过 tiny-tensorrt  去实现的，耗时也差不多 是 50ms 的样子； 不知道是不是因为异步的原因

**Comment by zerollzeng** [comment]
你还是没有描述清楚你的问题zzz, 我计划在TensorRT 8.0 版本release的时候做一次大的更新,会把dynamic shape更新上去,你可以发一份模型给我, 到时候我可以帮你测试一下

**Comment by xusk** [comment]
> 你还是没有描述清楚你的问题zzz, 我计划在TensorRT 8.0 版本release的时候做一次大的更新,会把dynamic shape更新上去,你可以发一份模型给我, 到时候我可以帮你测试一下

好的，感谢； 不过我刚刚发现 动态输入时候

profile = builder.create_optimization_profile()
profile.set_shape(network.get_input(0).name, (1, 3, 64, 64), (1, 3, 360, 640), (1, 3, 720, 1280))
config.add_optimization_profile(profile) 
set_shape 的值对结果影响很大

**Comment by xusk** [comment]
> > 你还是没有描述清楚你的问题zzz, 我计划在TensorRT 8.0 版本release的时候做一次大的更新,会把dynamic shape更新上去,你可以发一份模型给我, 到时候我可以帮你测试一下
> 
> 好的，感谢； 不过我刚刚发现 动态输入时候
> 
> profile = builder.create_optimization_profile()
> profile.set_shape(network.get_input(0).name, (1, 3, 64, 64), (1, 3, 360, 640), (1, 3, 720, 1280))
> config.add_optimization_profile(profile)
> set_shape 的值对结果影响很大

刚才调整了下这个 shape  (1, 3, 96, 128), (1, 3, 360, 640), (1, 3, 720, 1280) , 单次推理时间大概在 1ms~2ms ；十分感谢

**Comment by zerollzeng** [comment]
https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#opt_profiles 是optimal shape的影响吗?

**Comment by xusk** [comment]
> https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#opt_profiles 是optimal shape的影响吗?

 是的
