### ISSUE TITLE
Provides a complete Python API example

### ISSUE THREAD

**Issue by MAhaitao999** [zerollzeng/tiny-tensorrt#34]
@zerollzeng 
The python API example is incomplete. Can u provide a passed complete example such as yolov3 or OpenPose in python?
![image](https://user-images.githubusercontent.com/8710394/96962799-189a8b80-153a-11eb-8901-f745c8a35095.png)

**Comment by zerollzeng** [comment]
Updating... will describe it well on UserGuide, but won't add sample due to maintenance cost.

**Comment by MAhaitao999** [comment]
@zerollzeng Thank U! Looking forward to updating soon.

**Comment by zerollzeng** [comment]
Actually you can run help(pytrt) after import pytrt
