### ISSUE TITLE
你好，请问转onnx的时候，编写自己的plugin

### ISSUE THREAD

**Issue by gentlebreeze1** [zerollzeng/tiny-tensorrt#35]
DEFINE_BUILTIN_OP_IMPORTER函数里面creator->createPlugin(name.c_str(), &pluginFieldCollection);返回null

**Comment by zerollzeng** [comment]
@gentlebreeze1 could you specify your issue with more details? eg. with issue template.

**Comment by gentlebreeze1** [comment]
my onnxmodel have  a node named PLugin,so i change builtin_op_importers.cpp.
when i run parseFromFile() ,The program crashes at this line
nvinfer1::IPluginCreator* creator = registry->getPluginCreator(name.c_str(), "1","");
creator vaule is NUll.
Below is the modification I made@zerollzeng 
DEFINE_BUILTIN_OP_IMPORTER(Plugin)
{
    std::vector<nvinfer1::ITensor*> tensors;
    for (auto& input : inputs)
    {
        ASSERT(input.is_tensor(), nvonnxparser::ErrorCode::kUNSUPPORTED_NODE);
        tensors.push_back(&input.tensor());
    }
    OnnxAttrs attrs(node, ctx);
    auto name = attrs.get<std::string>("name", "");

    nvinfer1::IPluginRegistry* registry = getPluginRegistry();
    nvinfer1::IPluginCreator* creator = registry->getPluginCreator(name.c_str(), "1","");
    nvinfer1::PluginFieldCollection pluginFieldCollection;
    pluginFieldCollection.nbFields = 0;
    nvinfer1::IPluginV2 *gnPlugin = creator->createPlugin(name.c_str(), &pluginFieldCollection);
    nvinfer1::IPluginV2Layer* layer = ctx->network()->addPluginV2(tensors.data(), tensors.size(), *gnPlugin);
    RETURN_ALL_OUTPUTS(layer);
        }

**Comment by gentlebreeze1** [comment]
this is my onnx node.
![image](https://user-images.githubusercontent.com/27668596/103966319-987bdd80-519a-11eb-8509-9d1431c5d0ae.png)
i add plugin
const char* HSigmoid_PLUGIN_VERSION="1";
static const char* HSigmoid_PLUGIN_TYPE = "HSigmoidPlugin";
static const char* HSigmoid_PLUGIN_NAME = "HSigmoidPlugin_TRT"; //plugin_name = plugin_type + plugin_namespace
REGISTER_TENSORRT_PLUGIN(HSigmoidPluginCreator); @zerollzeng 
const char* HSigmoid_PLUGIN_NAMESPACE = "_TRT";

**Comment by zerollzeng** [comment]
If convenient could you post your plugin implementation? or send it to me via email. still very confused about your problem.

**Comment by gentlebreeze1** [comment]
what is Your email addresss?

**Comment by zerollzeng** [comment]
zerollzeng@gmail.com

**Comment by zerollzeng** [comment]
@gentlebreeze1 thanks for your feedback, unfortunately, I still didn't figure out the reason that leads to your problem(mostly cause by plugin namespace or something I think). so I rewrite a cute sample plugin implementation that can parse the demo.onnx model correctly, although I didn't write a correct implementation so it still crashes due to oom on forward. but your problem has been solved.

here are the steps that should work for you:
1. pull the latest commit and take a look at plugin/CuteSamplePlugin.
2. modify the plugin name in
https://github.com/zerollzeng/tiny-tensorrt/blob/9edc16cc6e6bab814a38253a110234ae18e64091/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp#L42
3. mkdir build && cd build && cmake -DBUILD_TEST=ON .. && make -j
4. runing test by ./build/unit_test --onnx_path /path/to/demo.onnx

and you should see the engine building is success. then I suggest you continue your work at this new workaround.

I will make more commits that elaborate on the plugin codes at the weekend. so the above might be change with new commits.

**Comment by gentlebreeze1** [comment]
thanks for your   reply@zerollzeng，do you mean that I don't need to modify builtin_op_importers.cpp?just create plugincreator?
but i get core crash.my log is
(๑¯◡¯๑) CUSTOM PLUGIN TRACE----> call [/disk2/tiny-tensorrt-master/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp][CuteSamplePluginCreator][Line 155] wow I run to here now
 (๑¯◡¯๑) CUSTOM PLUGIN TRACE----> call [/disk2/tiny-tensorrt-master/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp][getPluginName][Line 162] wow I run to here now
 (๑¯◡¯๑) CUSTOM PLUGIN TRACE----> call [/disk2/tiny-tensorrt-master/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp][getPluginName][Line 162] wow I run to here now
 (๑¯◡¯๑) CUSTOM PLUGIN TRACE----> call [/disk2/tiny-tensorrt-master/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp][getPluginVersion][Line 168] wow I run to here now
[2021-01-11 14:01:31.227] [info] create plugin factory
[2021-01-11 14:01:31.227] [info] yolo3 params: class: 1, netSize: 416 
[2021-01-11 14:01:31.227] [info] upsample params: scale: 2
[2021-01-11 14:01:31.712] [info] build onnx engine from /disk2/tiny-tensorrt-master/demo/demo.onnx...
----------------------------------------------------------------
Input filename:   /disk2/tiny-tensorrt-master/demo/demo.onnx
ONNX IR version:  0.0.4
Opset version:    9
Producer name:    pytorch
Producer version: 1.3
Domain:           
Model version:    0
Doc string:       
----------------------------------------------------------------
 (๑¯◡¯๑) CUSTOM PLUGIN TRACE----> call [/disk2/tiny-tensorrt-master/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp][getPluginVersion][Line 168] wow I run to here now
 (๑¯◡¯๑) CUSTOM PLUGIN TRACE----> call [/disk2/tiny-tensorrt-master/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp][createPlugin][Line 180] wow I run to here now
 (๑¯◡¯๑) CUSTOM PLUGIN TRACE----> call [/disk2/tiny-tensorrt-master/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp][CuteSamplePlugin][Line 32] wow I run to here now
 (๑¯◡¯๑) CUSTOM PLUGIN TRACE----> call [/disk2/tiny-tensorrt-master/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp][setPluginNamespace][Line 143] wow I run to here now
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
gdb message is
#0  0x00007fa9f0f79750 in nvinfer1::Network::containsTensor(nvinfer1::ITensor const&) const () from /disk2/workspace/trtinfer/libs/libnvinfer.so.7
#1  0x00007fa9f0f81504 in nvinfer1::Network::addPluginV2(nvinfer1::ITensor* const*, int, nvinfer1::IPluginV2&) ()
   from /disk2/workspace/trtinfer/libs/libnvinfer.so.7
#2  0x00007fa9ef3ffb21 in onnx2trt::(anonymous namespace)::importHSigmoid(onnx2trt::IImporterContext*, onnx2trt_onnx::NodeProto const&, std::vector<onnx2trt::TensorOrWeights, std::allocator<onnx2trt::TensorOrWeights> >&) ()
   from /disk2/workspace/trtinfer/libs/libnvonnxparser.so.7
#3  0x00007fa9ef4166a9 in std::_Function_handler<onnx2trt::ValueOrStatus<std::vector<onnx2trt::TensorOrWeights, std::allocator<onnx2trt::TensorOrWeights> > > (onnx2trt::IImporterContext*, onnx2trt_onnx::NodeProto const&, std::vector<onnx2trt::TensorOrWeights, std::allocator<onnx2trt::TensorOrWeights> >&), onnx2trt::ValueOrStatus<std::vector<onnx2trt::TensorOrWeights, std::allocator<onnx2trt::TensorOrWeights> > > (*)(onnx2trt::IImporterContext*, onnx2trt_onnx::NodeProto const&, std::vector<onnx2trt::TensorOrWeights, std::allocator<onnx2trt::TensorOrWeights> >&)>::_M_invoke(std::_Any_data const&, onnx2trt::IImporterContext*&&, onnx2trt_onnx::NodeProto const&, std::vector<onnx2trt::TensorOrWeights, std::allocator<onnx2trt::TensorOrWeights> >&) ()
   from /disk2/workspace/trtinfer/libs/libnvonnxparser.so.7
#4  0x00007fa9ef3c3277 in onnx2trt::parseGraph(onnx2trt::IImporterContext*, onnx2trt_onnx::GraphProto const&, bool, int*) ()
   from /disk2/workspace/trtinfer/libs/libnvonnxparser.so.7

**Comment by zerollzeng** [comment]
@gentlebreeze1 thanks for your feedback, seems my custom onnx plugin template still have some bugs now. will fix ASAP

**Comment by gentlebreeze1** [comment]
@zerollzeng Is it a version issue?my tensorrt version is 7.0

**Comment by zerollzeng** [comment]
> thanks for your reply@zerollzeng，do you mean that I don't need to modify builtin_op_importers.cpp?just create plugincreator?

yeah, I only use your demo.onnx

**Comment by zerollzeng** [comment]
> @zerollzeng Is it a version issue?my tensorrt version is 7.0

I run it in the latest docker images

**Comment by zerollzeng** [comment]
@gentlebreeze1  could you try it with version 7.20+? the newest version is preferred.

**Comment by gentlebreeze1** [comment]
> @gentlebreeze1 could you try it with version 7.20+? the newest version is preferred.

ok,i will try

**Comment by zerollzeng** [comment]
@gentlebreeze1 it can run successfully on the latest version of tensorrt. try upgrade your tensorrt version

**Comment by gentlebreeze1** [comment]
> @gentlebreeze1 it can run successfully on the latest version of tensorrt. try upgrade your tensorrt version


NVIDIA official website seems to have some problems.i cant download anything!do you have TensorRT 7.2.1 for Ubuntu 16.04 and CUDA 11.0 TAR package?

**Comment by zerollzeng** [comment]
> NVIDIA official website seems to have some problems.i cant download anything!do you have TensorRT 7.2.1 for Ubuntu 16.04 and CUDA 11.0 TAR package?

Sry I tested on docker.

**Comment by gentlebreeze1** [comment]
> > NVIDIA official website seems to have some problems.i cant download anything!do you have TensorRT 7.2.1 for Ubuntu 16.04 and CUDA 11.0 TAR package?
> 
> Sry I tested on docker.

tensorrt 7.2.1 cuda11.0 cudnn8.0 can suceess.
thanks,by the way , do you have implemented tensorrt of  yolov5?my onnx cant export detect layer.

**Comment by zerollzeng** [comment]
> do you have implemented tensorrt of yolov5?my onnx cant export detect layer

no, but you can search in github, I've seen some related project :)

> tensorrt 7.2.1 cuda11.0 cudnn8.0 can success.

Have any test on 7.2.0 and 7.1.3, I guess it should work for 7.2.0+ but fail on previous versions, haven't so much time to test, is you do so, please give me some feedback. Thanks a lot!

**Comment by gentlebreeze1** [comment]
i meet a strang problem. int8 result is different from float16. do int8 have some problem?

**Comment by zerollzeng** [comment]
> I meet a strange problem. int8 result is different from float16. do int8 have some problem?

for the int8 plugin, make sure you implement a forward function that's for int8, and if not, when run in int8 mode, the plugin will fallback to fp32. also please keep in mind that the int8 mode needs an extra calibration phase.

**Comment by gentlebreeze1** [comment]
> for the int8 plugin, make sure you implement a forward function that's for int8, and if not, when run in int8 mode, the plugin will fallback to fp32. also please keep in mind that the int8 mode needs an extra calibration phase.
my onnx do not have extra layers.and i use 2000 images to set  calibration.
i convert yolov5.onnx, do you have time to solve the problem?@zerollzeng

**Comment by zerollzeng** [comment]
> my onnx does not have extra layers. and I use 2000 images to set calibration.
> I convert yolov5.onnx, do you have time to solve the problem?@zerollzeng

what problem? if the calibration was successful, then you should get a similiar detect result, maybe lower in accuracy sligntly. but you will get the right detection result.

**Comment by gentlebreeze1** [comment]
> > my onnx does not have extra layers. and I use 2000 images to set calibration.
> > I convert yolov5.onnx, do you have time to solve the problem?@zerollzeng
> 
> what problem? if the calibration was successful, then you should get a similiar detect result, maybe lower in accuracy sligntly. but you will get the right detection result.

int8 conf is so low, i set conf to 0.005 to get the result.float16 conf is 0.5.

**Comment by zerollzeng** [comment]
> int8 conf is so low, I set conf to 0.005 to get the result.float16 conf is 0.5.

check your code, sry I can't help you with this question, since I don't familiar with the details of yolov5, but I think it should be related to your plugin implementation or insufficient calibration data(although I think 2000 is enough), check your plugin implementation carefully and compare the input and output of plugin between fp32 and int8, you should make it work finally.
