### ISSUE TITLE
*(-v-)* I customized the onnx plugin according to your tutorial

### ISSUE THREAD

**Issue by nanmi** [zerollzeng/tiny-tensorrt#36]
I modified cutesampleplugin/ CuteSamplePlugin.cpp Cute_ PLUGIN_ Name, but after cmake / make, I still can't find my custom operator.

**Describe the bug**
```
 (๑¯◡¯๑) CUSTOM PLUGIN TRACE----> call [/root/tiny-tensorrt/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp][CuteSamplePluginCreator][Line 155] wow I run to here now
 (๑¯◡¯๑) CUSTOM PLUGIN TRACE----> call [/root/tiny-tensorrt/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp][getPluginName][Line 162] wow I run to here now
 (๑¯◡¯๑) CUSTOM PLUGIN TRACE----> call [/root/tiny-tensorrt/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp][getPluginName][Line 162] wow I run to here now
 (๑¯◡¯๑) CUSTOM PLUGIN TRACE----> call [/root/tiny-tensorrt/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp][getPluginVersion][Line 168] wow I run to here now
[2021-01-10 13:45:11.894] [info] create plugin factory
[2021-01-10 13:45:11.895] [info] yolo3 params: class: 1, netSize: 416 
[2021-01-10 13:45:11.895] [info] upsample params: scale: 2
[2021-01-10 13:45:14.373] [info] build onnx engine from yolov3-10-siim.onnx...
----------------------------------------------------------------
Input filename:   yolov3-10-siim.onnx
ONNX IR version:  0.0.5
Opset version:    10
Producer name:    keras2onnx
Producer version: 1.5.1
Domain:           onnx
Model version:    0
Doc string:       
----------------------------------------------------------------
onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
While parsing node number 283 [NonMaxSuppression]:
ERROR: ModelImporter.cpp:134 In function parseGraph:
[8] No importer registered for op: NonMaxSuppression
[2021-01-10 13:45:14.822] [error] error: could not parse onnx engine
[2021-01-10 13:45:14.822] [error] error: could not deserialize or build engine
Segmentation fault (core dumped)
```

**To Reproduce**
1. I modified cutesampleplugin/ CuteSamplePlugin.cpp Cute_ PLUGIN_ Name=NonMaxSuppression
2. ./unit_test --onnx_path yolov3-10-sim.onnx

**Screenshots**
my network use netron:
![image](https://user-images.githubusercontent.com/37356276/104141921-10911000-53f4-11eb-9a89-9bb7937ef4fc.png)
my tensorrt folder:
![image](https://user-images.githubusercontent.com/37356276/104141973-4c2bda00-53f4-11eb-8c54-0d2968921846.png)
plugin readme:
![image](https://user-images.githubusercontent.com/37356276/104141994-6bc30280-53f4-11eb-9ea6-ceeb8990502e.png)

**System environment (please complete the following information):**
 - Device:docker contain
 - OS:ubuntu18.04
 - Driver version:418.165.02
 - CUDA version:10.2
 - TensorRT version:TensorRT-7.0.0.11
 - Others:nvidia GPU:four Tesla P100 

**Cmake output**
```
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "10.2") 
-- CUDA supported archs: 60;61;70;75
-- CUDA targeted archs: 60;61;70;75
-- Found TensorRT headers at TENSORRT_INCLUDE_DIR-NOTFOUND
-- 
Generated gencode flags:  -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_75,code=sm_75 -gencode arch=compute_75,code=compute_75 
BUILD_PYTHON : OFF 
BUILD_TEST : ON 
ENABLE_PRELU_FP16 : OFF 

-- Configuring done
-- Generating done
-- Build files have been written to: /root/tiny-tensorrt/build
```

**Running output**
```
 (๑¯◡¯๑) CUSTOM PLUGIN TRACE----> call [/root/tiny-tensorrt/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp][CuteSamplePluginCreator][Line 155] wow I run to here now
 (๑¯◡¯๑) CUSTOM PLUGIN TRACE----> call [/root/tiny-tensorrt/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp][getPluginName][Line 162] wow I run to here now
 (๑¯◡¯๑) CUSTOM PLUGIN TRACE----> call [/root/tiny-tensorrt/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp][getPluginName][Line 162] wow I run to here now
 (๑¯◡¯๑) CUSTOM PLUGIN TRACE----> call [/root/tiny-tensorrt/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp][getPluginVersion][Line 168] wow I run to here now
[2021-01-11 02:09:45.353] [info] create plugin factory
[2021-01-11 02:09:45.353] [info] yolo3 params: class: 1, netSize: 416 
[2021-01-11 02:09:45.353] [info] upsample params: scale: 2
[2021-01-11 02:09:47.796] [info] build onnx engine from /root/yolov3-10-sim.onnx...
----------------------------------------------------------------
Input filename:   /root/yolov3-10-sim.onnx
ONNX IR version:  0.0.5
Opset version:    10
Producer name:    keras2onnx
Producer version: 1.5.1
Domain:           onnx
Model version:    0
Doc string:       
----------------------------------------------------------------
onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
onnx2trt_utils.cpp:222: One or more weights outside the range of INT32 was clamped
onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
While parsing node number 283 [NonMaxSuppression]:
ERROR: ModelImporter.cpp:134 In function parseGraph:
[8] No importer registered for op: NonMaxSuppression
[2021-01-11 02:09:48.216] [error] error: could not parse onnx engine
[2021-01-11 02:09:48.216] [error] error: could not deserialize or build engine
Segmentation fault (core dumped)
```

**Comment by zerollzeng** [comment]
Thanks for your feedback. Can you share your yolov3 model with me via email or google drive? or other ways that are convenient to you(please don't use baidu net drive, eg. it's painfully slow)

**Comment by nanmi** [comment]
> 感谢您的反馈意见。您可以通过电子邮件或Google云端硬盘与我分享您的yolov3模型吗？或其他方便的方式（请不要使用百度网盘，例如，速度太慢）



> Thanks for your feedback. Can you share your yolov3 model with me via email or google drive? or other ways that are convenient to you(please don't use baidu net drive, eg. it's painfully slow)

ok, i have share with you my onnx model with https://drive.google.com/file/d/14JHWCht3ISpJuEUs-Lf-798mjUZka2NP/view?usp=sharing

**Comment by zerollzeng** [comment]
already downloaded. I will test your model at lunch break.

**Comment by nanmi** [comment]
> downloading. I will test your model at lunch break.

thanks a lot

**Comment by zerollzeng** [comment]
@nanmi try using latest TensorRT, eg via docker. I use nvcr.io/nvidia/tensorrt:20.12-py3 it can found the plugin successfully.

**Comment by zerollzeng** [comment]
please pull the latest code(which I disable a lot debug information), and you should get the output like:
```
root@24f92bff44ea:/tiny-tensorrt/build# ./unit_test --onnx_path ../onnx/yolov3-10-sim.onnx 
 (๑¯◡¯๑) CUSTOM PLUGIN TRACE----> call [/tiny-tensorrt/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp][CuteSamplePluginCreator][Line 155] wow I run to here now
 (๑¯◡¯๑) CUSTOM PLUGIN TRACE----> call [/tiny-tensorrt/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp][getPluginName][Line 162] wow I run to here now
 (๑¯◡¯๑) CUSTOM PLUGIN TRACE----> call [/tiny-tensorrt/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp][getPluginName][Line 162] wow I run to here now
 (๑¯◡¯๑) CUSTOM PLUGIN TRACE----> call [/tiny-tensorrt/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp][getPluginVersion][Line 168] wow I run to here now
[2021-01-11 11:54:38.942] [info] create plugin factory
[2021-01-11 11:54:38.943] [info] yolo3 params: class: 1, netSize: 416 
[2021-01-11 11:54:38.943] [info] upsample params: scale: 2
[2021-01-11 11:54:38.987] [info] build onnx engine from ../onnx/yolov3-10-sim.onnx...
----------------------------------------------------------------
Input filename:   ../onnx/yolov3-10-sim.onnx
ONNX IR version:  0.0.5
Opset version:    10
Producer name:    keras2onnx
Producer version: 1.5.1
Domain:           onnx
Model version:    0
Doc string:       
----------------------------------------------------------------
/workspace/TensorRT/parsers/onnx/onnx2trt_utils.cpp:218: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
/workspace/TensorRT/parsers/onnx/onnx2trt_utils.cpp:246: One or more weights outside the range of INT32 was clamped
/workspace/TensorRT/parsers/onnx/onnx2trt_utils.cpp:246: One or more weights outside the range of INT32 was clamped
/workspace/TensorRT/parsers/onnx/ModelImporter.cpp:139: No importer registered for op: NonMaxSuppression. Attempting to import as plugin.
/workspace/TensorRT/parsers/onnx/builtin_op_importers.cpp:3716: Searching for plugin: NonMaxSuppression, plugin_version: 1, plugin_namespace: 
 (๑¯◡¯๑) CUSTOM PLUGIN TRACE----> call [/tiny-tensorrt/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp][getPluginVersion][Line 168] wow I run to here now
 (๑¯◡¯๑) CUSTOM PLUGIN TRACE----> call [/tiny-tensorrt/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp][getFieldNames][Line 174] wow I run to here now
 (๑¯◡¯๑) CUSTOM PLUGIN TRACE----> call [/tiny-tensorrt/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp][createPlugin][Line 180] wow I run to here now
 (๑¯◡¯๑) CUSTOM PLUGIN TRACE----> call [/tiny-tensorrt/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp][CuteSamplePlugin][Line 32] wow I run to here now
 (๑¯◡¯๑) CUSTOM PLUGIN TRACE----> call [/tiny-tensorrt/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp][setPluginNamespace][Line 143] wow I run to here now
/workspace/TensorRT/parsers/onnx/builtin_op_importers.cpp:3733: Successfully created plugin: NonMaxSuppression
 (๑¯◡¯๑) CUSTOM PLUGIN TRACE----> call [/tiny-tensorrt/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp][getNbOutputs][Line 43] wow I run to here now
 (๑¯◡¯๑) CUSTOM PLUGIN TRACE----> call [/tiny-tensorrt/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp][getOutputDataType][Line 67] wow I run to here now
 (๑¯◡¯๑) CUSTOM PLUGIN TRACE----> call [/tiny-tensorrt/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp][CuteSamplePlugin][Line 32] wow I run to here now
 (๑¯◡¯๑) CUSTOM PLUGIN TRACE----> call [/tiny-tensorrt/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp][setPluginNamespace][Line 143] wow I run to here now
 (๑¯◡¯๑) CUSTOM PLUGIN TRACE----> call [/tiny-tensorrt/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp][getNbOutputs][Line 43] wow I run to here now
yolonms_layer_1/non_max_suppression/NonMaxSuppressionV3: PluginV2Layer must be V2DynamicExt when there are runtime input dimensions.
yolonms_layer_1/non_max_suppression/NonMaxSuppressionV3: PluginV2Layer must be V2DynamicExt when there are runtime input dimensions.
yolonms_layer_1/non_max_suppression/NonMaxSuppressionV3: PluginV2Layer must be V2DynamicExt when there are runtime input dimensions.
[2021-01-11 11:54:39.429] [info] fp16 support: false
[2021-01-11 11:54:39.429] [info] int8 support: false
[2021-01-11 11:54:39.429] [info] Max batchsize: 4
[2021-01-11 11:54:39.429] [info] Max workspace size: 10485760
[2021-01-11 11:54:39.429] [info] Number of DLA core: 0
[2021-01-11 11:54:39.429] [info] Max DLA batchsize: 268435456
[2021-01-11 11:54:39.429] [info] Current use DLA core: 0
[2021-01-11 11:54:39.429] [info] build engine...
yolonms_layer_1/non_max_suppression/NonMaxSuppressionV3: PluginV2Layer must be V2DynamicExt when there are runtime input dimensions.
yolonms_layer_1/non_max_suppression/NonMaxSuppressionV3: PluginV2Layer must be V2DynamicExt when there are runtime input dimensions.
Layer yolonms_layer_1/non_max_suppression/NonMaxSuppressionV3 failed validation
Network validation failed.
unit_test: /tiny-tensorrt/Trt.cpp:310: void Trt::BuildEngine(): Assertion `mEngine != nullptr' failed.
Aborted (core dumped)
```
which mean you need to derive PluginV2DynamicExt class.

**Comment by nanmi** [comment]
> please pull the latest code(which I disable a lot debug information), and you should get the output like:
> 
> ```
> root@24f92bff44ea:/tiny-tensorrt/build# ./unit_test --onnx_path ../onnx/yolov3-10-sim.onnx 
>  (๑¯◡¯๑) CUSTOM PLUGIN TRACE----> call [/tiny-tensorrt/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp][CuteSamplePluginCreator][Line 155] wow I run to here now
>  (๑¯◡¯๑) CUSTOM PLUGIN TRACE----> call [/tiny-tensorrt/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp][getPluginName][Line 162] wow I run to here now
>  (๑¯◡¯๑) CUSTOM PLUGIN TRACE----> call [/tiny-tensorrt/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp][getPluginName][Line 162] wow I run to here now
>  (๑¯◡¯๑) CUSTOM PLUGIN TRACE----> call [/tiny-tensorrt/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp][getPluginVersion][Line 168] wow I run to here now
> [2021-01-11 11:54:38.942] [info] create plugin factory
> [2021-01-11 11:54:38.943] [info] yolo3 params: class: 1, netSize: 416 
> [2021-01-11 11:54:38.943] [info] upsample params: scale: 2
> [2021-01-11 11:54:38.987] [info] build onnx engine from ../onnx/yolov3-10-sim.onnx...
> ----------------------------------------------------------------
> Input filename:   ../onnx/yolov3-10-sim.onnx
> ONNX IR version:  0.0.5
> Opset version:    10
> Producer name:    keras2onnx
> Producer version: 1.5.1
> Domain:           onnx
> Model version:    0
> Doc string:       
> ----------------------------------------------------------------
> /workspace/TensorRT/parsers/onnx/onnx2trt_utils.cpp:218: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
> /workspace/TensorRT/parsers/onnx/onnx2trt_utils.cpp:246: One or more weights outside the range of INT32 was clamped
> /workspace/TensorRT/parsers/onnx/onnx2trt_utils.cpp:246: One or more weights outside the range of INT32 was clamped
> /workspace/TensorRT/parsers/onnx/ModelImporter.cpp:139: No importer registered for op: NonMaxSuppression. Attempting to import as plugin.
> /workspace/TensorRT/parsers/onnx/builtin_op_importers.cpp:3716: Searching for plugin: NonMaxSuppression, plugin_version: 1, plugin_namespace: 
>  (๑¯◡¯๑) CUSTOM PLUGIN TRACE----> call [/tiny-tensorrt/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp][getPluginVersion][Line 168] wow I run to here now
>  (๑¯◡¯๑) CUSTOM PLUGIN TRACE----> call [/tiny-tensorrt/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp][getFieldNames][Line 174] wow I run to here now
>  (๑¯◡¯๑) CUSTOM PLUGIN TRACE----> call [/tiny-tensorrt/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp][createPlugin][Line 180] wow I run to here now
>  (๑¯◡¯๑) CUSTOM PLUGIN TRACE----> call [/tiny-tensorrt/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp][CuteSamplePlugin][Line 32] wow I run to here now
>  (๑¯◡¯๑) CUSTOM PLUGIN TRACE----> call [/tiny-tensorrt/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp][setPluginNamespace][Line 143] wow I run to here now
> /workspace/TensorRT/parsers/onnx/builtin_op_importers.cpp:3733: Successfully created plugin: NonMaxSuppression
>  (๑¯◡¯๑) CUSTOM PLUGIN TRACE----> call [/tiny-tensorrt/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp][getNbOutputs][Line 43] wow I run to here now
>  (๑¯◡¯๑) CUSTOM PLUGIN TRACE----> call [/tiny-tensorrt/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp][getOutputDataType][Line 67] wow I run to here now
>  (๑¯◡¯๑) CUSTOM PLUGIN TRACE----> call [/tiny-tensorrt/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp][CuteSamplePlugin][Line 32] wow I run to here now
>  (๑¯◡¯๑) CUSTOM PLUGIN TRACE----> call [/tiny-tensorrt/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp][setPluginNamespace][Line 143] wow I run to here now
>  (๑¯◡¯๑) CUSTOM PLUGIN TRACE----> call [/tiny-tensorrt/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp][getNbOutputs][Line 43] wow I run to here now
> yolonms_layer_1/non_max_suppression/NonMaxSuppressionV3: PluginV2Layer must be V2DynamicExt when there are runtime input dimensions.
> yolonms_layer_1/non_max_suppression/NonMaxSuppressionV3: PluginV2Layer must be V2DynamicExt when there are runtime input dimensions.
> yolonms_layer_1/non_max_suppression/NonMaxSuppressionV3: PluginV2Layer must be V2DynamicExt when there are runtime input dimensions.
> [2021-01-11 11:54:39.429] [info] fp16 support: false
> [2021-01-11 11:54:39.429] [info] int8 support: false
> [2021-01-11 11:54:39.429] [info] Max batchsize: 4
> [2021-01-11 11:54:39.429] [info] Max workspace size: 10485760
> [2021-01-11 11:54:39.429] [info] Number of DLA core: 0
> [2021-01-11 11:54:39.429] [info] Max DLA batchsize: 268435456
> [2021-01-11 11:54:39.429] [info] Current use DLA core: 0
> [2021-01-11 11:54:39.429] [info] build engine...
> yolonms_layer_1/non_max_suppression/NonMaxSuppressionV3: PluginV2Layer must be V2DynamicExt when there are runtime input dimensions.
> yolonms_layer_1/non_max_suppression/NonMaxSuppressionV3: PluginV2Layer must be V2DynamicExt when there are runtime input dimensions.
> Layer yolonms_layer_1/non_max_suppression/NonMaxSuppressionV3 failed validation
> Network validation failed.
> unit_test: /tiny-tensorrt/Trt.cpp:310: void Trt::BuildEngine(): Assertion `mEngine != nullptr' failed.
> Aborted (core dumped)
> ```
> 
> which mean you need to derive PluginV2DynamicExt class.

Allyes!!! it works, thank you very much :)
