### ISSUE TITLE
Adding the Custom Plugin Node

### ISSUE THREAD

**Issue by Darshcg** [zerollzeng/tiny-tensorrt#38]
Hi @zerollzeng,
Thank you very much for your Project. I found it very helpful.

Just to Introduce my issue: Actually, I have a custom models built from Pytorch, I have converted .pt to .onnx, but there are two Ops which are not supported in TensorRT. So, I am thinking of adding and custom plugins of those two unsupported Ops in TensorRT.
So, after searching more about adding custom plugins, luckily I found your Project. Having said that, I was following the steps mentioned here:(https://github.com/zerollzeng/tiny-tensorrt/tree/master/plugin/CuteSamplePlugin), but I am stuck at adding the code for the Custom plugin Node. Can you please assist me in adding the Custom plugin Node? would be a great help from yourside.

Thanks in Advance,
Darshan C G

**Comment by zerollzeng** [comment]
@Darshcg  ok, Let's see what I can help. also thanks for trying tiny-tensorrt. but I'm quite busy these days, so might no reply very often. 
if you are not familiar with tensorrt plugin, I recommend you to read the official tensorrt developer guide and API doc carefully. it clarifies the usage of plugin api.

**Comment by zerollzeng** [comment]
Closed due to inativity
