### ISSUE TITLE
Regarding the Custom Plugin 

### ISSUE THREAD

**Issue by Darshcg** [zerollzeng/tiny-tensorrt#40]
Hi @zerollzeng,

Thanks for your Amazing Work. It helped me a lot.

I have two Ops that are unsupported in TRT. I was referring to your Tutorial on registering them. I have doubt on the same: 
1.) What are the Changes that have to be made in this File(https://github.com/zerollzeng/tiny-tensorrt/blob/master/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp)? For example, I want to Implement the Cutom Plugin for an Op called "**Einsum**", So what is that i need to modify in this Script(https://github.com/zerollzeng/tiny-tensorrt/blob/master/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp)?

Thanks and Regards,
Darshan C G

**Comment by zerollzeng** [comment]
hi @Darshcg 
The CuteSamplePlugin is a very clean plugin implementation, all it is done now is make tensorrt find your plugin, you need to implement the function of [IPluginV2Ext](https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_plugin_v2_ext.html) based on your plugin, eg, return the correct output of your plugin, what datatype it supports, how it run during forward.

I have to said that implement a custom plugin from scratch is a difficult work, you can mimic the [official implementation](https://github.com/NVIDIA/TensorRT/tree/master/plugin)

**Comment by Darshcg** [comment]
Hi @zerollzeng,

Thanks for your kind response.

Actually, I am Implementing a Custom Plugin for RoI Align Op. I am having a Small Doubt on Serialisation and deserialization of the Variables(https://github.com/zerollzeng/tiny-tensorrt/blob/60e344f652925dcb98988dbaab762461b5e6a08c/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp#L35 and https://github.com/zerollzeng/tiny-tensorrt/blob/60e344f652925dcb98988dbaab762461b5e6a08c/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp#L83).


The information of the Op has been provided in the Pic attached below:
![Screenshot from 2021-02-16 01-20-21](https://user-images.githubusercontent.com/48723743/107988831-da4c3f00-6ff6-11eb-87e2-201cb51f2bd8.png)
I am actually having doubt in taking the variables in Serialisation and deserialization functions. Among the Attributes and the Inputs we have(in the above pic) which all variables needs to be serialised? And what is the Output Dimension of that Node?

If you can assist me in this, would be a great help from yourside.

Thanks in advance,
Darshan

**Comment by zerollzeng** [comment]
> I am actually having doubt in taking the variables in Serialisation and deserialization functions. Among the Attributes and the Inputs we have(in the above pic) which all variables needs to be serialised? And what is the Output Dimension of that Node?

All the variables and weights need to be serialized so that it can recover those ops from serialized engine file(recommended). and about the output dimension, you need to figure it out by yourself :), it depends on your op.

btw can you search roi align implementation on the official repo? it's pretty common on computer vision. so other people might have done it.

**Comment by Darshcg** [comment]
Hi @zerollzeng,

I have completed the Implementation of the Plugin for RoI Align Op. 
I have attached the link for the .cu File of that Plugin below.
https://drive.google.com/file/d/1MXoWEkyzQpE8DDbtQQzV4glCHkJ4IJsu/view?usp=sharing

If you can just have a look at the script and check if anything wrong in it, would be a great help from yourside.

Best regards,
Darshan.

**Comment by Darshcg** [comment]
Hi @zerollzeng,
I just wanted to know whether everything is correct in the above script or if there is anything wrong that needs to be corrected. Since this is the first time I am implementing, so the reason asking for your help.

Thanks again for your support,
Darshan

**Comment by zerollzeng** [comment]
@Darshcg Take a glance quickly, your implementation looks good to me, can you get the correct output?

**Comment by Darshcg** [comment]
@zerollzeng Thank you very much for your kind reply. I will have a look at the PRelu Plugin Implementation to get more details.

@zerollzeng Btw, I am also implementing a Custom plugin for an **Einsum op**(which is not currently supported in TRT). 
Actually, I was having doubt in enqueue().

Below is the Einsum Node Information.
![Screenshot from 2021-02-18 15-27-02](https://user-images.githubusercontent.com/48723743/108339888-fbcb4780-71fd-11eb-853d-f0fad9530e65.png)

I have Implemented the plugin, but I was having a doubt in Transposing the Inputs in the enqueue().
Below the snippet of the equeue() function.

```
int EinsumPlugin::enqueue(int batchSize, const void *const *inputs, void **outputs, void *workspace, cudaStream_t stream)
{
cublasHandle_t mCublas;
CHECK(cublasCreate(&mCublas));
float onef{1.0f}, zerof{0.0f};
float transpose_1[N][O][L];
float transpose[N][K][L];

cublasSetStream(mCublas, stream);

if(equation== 'nct,ncp->ntp')
{
   
   //Transpose the matrix A
  for(int k=0; k< N; ++k)
   for (int i = 0; i < L; ++i)
        for (int j = 0; j < K; ++j) {
            transpose[k][j][i] = inputs[0][k][i][j];
        }


   cublasSgemmBatched(mCublas, CUBLAS_OP_N,CUBLAS_OP_N, 
                                  M, L, K, onef, 
                                  reinterpret_cast<const float*>(inputs[1]), M, 
                                  reinterpret_cast<const float*>(transpose), K, 
                                  zerof, reinterpret_cast<const float*>(outputs[0]), M, N)


}

else if(equation=='ntg, ncg -> nct')
{
   //Transpose the matrix B
  for(int a=0; a< N; ++a)
   for (int b = 0; b < O; ++b)
        for (int c = 0; c < M; ++c) {
            transpose[a][c][b] = inputs[1][a][b][c];
        }

   cublasSgemmBatched(mCublas, CUBLAS_OP_N,CUBLAS_OP_N, 
                                  M, L, K, onef, 
                                  reinterpret_cast<const float*>(transpose), M, 
                                  reinterpret_cast<const float*>(inputs[0]), K, 
                                  zerof, reinterpret_cast<const float*>(outputs[0]), M, N)

   //Transpose the output matrix 
  for(int e=0; e< N; ++e)
   for (int f = 0; f < O; ++f)
        for (int g = 0; g < M; ++g) {
            transpose_1[e][g][f] = outputs[0][e][f][g];
        }

   //Transpose the matrix results
  for(int e=0; e< N; ++e)
   for (int f = 0; f < O; ++f)
        for (int g = 0; g < M; ++g) {
            outputs[0][e][f][g] = transpose_1[e][f][g];
        }

}

return 0;
}
```
I am facing an error: **error: expression must be a pointer to a complete object type in the line  transpose[k][j][i] = inputs[0][k][i][j];**. May I know what is the eaxct error and how to resolve this?

Thanks,
Darshan

**Comment by Darshcg** [comment]
Hi @zerollzeng,

I have solved it.
Thanks for your Help.

Regards,
Darshan

**Comment by zerollzeng** [comment]
Sry didn't reply due to work, I'm glad you solved your problem, and thanks for trying tiny-tensorrt:)
