### ISSUE TITLE
自定义插件输入类型

### ISSUE THREAD

**Issue by chenxyyy** [zerollzeng/tiny-tensorrt#42]
大佬您好，看了您的工程，学到了很多东西。非常感谢

但是我有一个问题，我目前在做的神经网络是以字典为输入的，请问在编写自定义插件时候，tensorrt支持这种输入嘛？

**Comment by zerollzeng** [comment]
nlp的网络吗？字典输入是指python里面的字典？应该要向量化再输入吧，可以描述得更清楚吗

**Comment by chenxyyy** [comment]
我做的是一个点云检测的网络。输入是一个对象，包含以下成员变量：
1. 三维格式的特征向量，torch::tensor [15249, 3]
2. 坐标 torch::tensor [15249, 4]
3. 输入尺寸 list 大小为3
4. batchsize  int  
5. 向量与坐标对应关系，字典格式

请问一下，这种tensorrt能否支持啊？如果不支持的话，我自己修改的话，工作量大吗？最近遇到了很多坑。。。

**Comment by zerollzeng** [comment]
> 请问一下，这种tensorrt能否支持啊？如果不支持的话，我自己修改的话，工作量大吗？最近遇到了很多坑。。。

据我所知应该不支持dict类型的输入，你想办法转成tensor再处理吧，你这个对应关系的dict是固定长度的吗？如果是的话就容易得多，不是的话会比较麻烦。

**Comment by chenxyyy** [comment]
> > 请问一下，这种tensorrt能否支持啊？如果不支持的话，我自己修改的话，工作量大吗？最近遇到了很多坑。。。
> 
> 据我所知应该不支持dict类型的输入，你想办法转成tensor再处理吧，你这个对应关系的dict是固定长度的吗？如果是的话就容易得多，不是的话会比较麻烦。

不是固定长度，是根据输入的尺度决定的，了解了。看来比较麻烦。

多谢您的回复啦。感谢O(∩_∩)O哈哈~

**Comment by zerollzeng** [comment]
谢谢你尝试tiny-tensorrt, 可以请问一下你是做什么方向的？像这种场景多不多？如果多的话我考虑看看能不能做一些支持 @chenxyyy

**Comment by chenxyyy** [comment]
我是做三维点云检测的，场景还是很多的，自动驾驶方面基本都会用。我用的是[SECOND](https://github.com/traveller59/second.pytorch)目标检测算法，其中用到了3D稀疏卷积，想把它写成插件，但是遇到了好多坑。

要是能得到大佬的支持，就太好了。

**Comment by chenxyyy** [comment]
我是做三维点云检测的，场景还是很多的，自动驾驶方面基本都会用。我用的是[SECOND](https://github.com/traveller59/second.pytorch)目标检测算法，其中用到了3D稀疏卷积，想把它写成插件，但是遇到了好多坑。

要是能得到大佬的支持，就太好了。

**Comment by sissini** [comment]
> 我是做三维点云检测的，场景还是很多的，自动驾驶方面基本都会用。我用的是[SECOND](https://github.com/traveller59/second.pytorch)目标检测算法，其中用到了3D稀疏卷积，想把它写成插件，但是遇到了好多坑。
> 
> 要是能得到大佬的支持，就太好了。

请问大佬们3D稀疏卷积onnx和tensorrt的插件实现了吗？想要部署带有spconv的网络，坑是不是巨多，不知道应该pytorch-onnx-tensorrt还是torch2tensorrt。 淌过的spconv加算子的坑，有没有什么经验之谈？感谢～

**Comment by chenxyyy** [comment]
@sissini 

spconv加算子的坑太深，没爬上来。

我使用了一些其他的手段做的加速，最后也做到了非常快的推理速度

**Comment by ShaunYang1** [comment]
@chenxyyy 
 大佬可以简单讲讲思路吗， 也卡在spconv了，估计了下工作量差点晕了
