### ISSUE TITLE
terminate called after throwing an instance of 'pwgen::PwgenException' what(): Driver error

### ISSUE THREAD

**Issue by Darshcg** [zerollzeng/tiny-tensorrt#43]
Hi @zerollzeng ,

During conversion from onnx to TRT I am getting an error as: terminate called after throwing an instance of 'pwgen::PwgenException' what(): Driver error. May I know the cause of this error?

Thanks,
Darshan

**Comment by zerollzeng** [comment]
sry I don't know the cause of this, google or official tensorrt repo should be helpful :)

**Comment by Darshcg** [comment]
Hi @zerollzeng,

Thank you for your response.
Reinstalling Driver, CUDA, CUDNN, TRT has solved this issue.

Thanks
