### ISSUE TITLE
[TensorRT] ERROR: ../rtSafe/cuda/reformat.cu (925) - Cuda Error in NCHWToNCHHW2: 400 (invalid resource handle)

### ISSUE THREAD

**Issue by Darshcg** [zerollzeng/tiny-tensorrt#45]
Hi @zerollzeng,

I have converted my Pytorch model to ONNX and to TRT.
But I am using another TRT(2) Model whose output will be as input to the above TRT(1) Model. while doing an Inference on these two TRT Models, I am getting error as:
**[TensorRT] ERROR: ../rtSafe/cuda/reformat.cu (925) - Cuda Error in NCHWToNCHHW2: 400 (invalid resource handle)
[TensorRT] ERROR: FAILED_EXECUTION: std::exception**

Not sure what is going wrong. what is causing an Issue here? 
Can you please assist me in resolving this error?

Thanks,
Darshan

**Comment by zerollzeng** [comment]
again please do not file issues that are unrelated to tiny-tensorrt, ask them on an official repo, read the guide, google it instead pls.
I won't answer the further unrelated questions.

thanks.
