### ISSUE TITLE
您好，使用onnx的model，发现问题。

### ISSUE THREAD

**Issue by duoduo1018** [zerollzeng/tiny-tensorrt#46]
你在#27指出：  “that's because for caffe you must specify the output name, but for onnx you don't need to specify it.”  
 在使用centerface.onnx 时候，其输出是“537”，“538”，“539”，“540”，     
1. 如果不指定输出的话，得到的是“537”层的输出；
2. 如果指定输出：std::vector<std::string> outputBlobname｛"537","538","539","540"}; 也只会得到“537“层的输出
3. 如果单独指定 “540” 其输出个数为：1280个（不是6400）

这个问题出现在哪里啊？ 应该怎样改呢
![网络图](https://user-images.githubusercontent.com/19523284/115004226-2a516000-9ed9-11eb-8b03-8e45036e77b8.jpg)

**Comment by zerollzeng** [comment]
Hi @duoduo1018, Thanks for using tiny-tensorrt
Can you share your model with me? Or a minimal subgraph that can reproduce this. Thanks

**Comment by duoduo1018** [comment]
> Hi @duoduo1018, Thanks for using tiny-tensorrt
> Can you share your model with me? Or a minimal subgraph that can reproduce this. Thanks
centerface.onnx,   this one .

**Comment by duoduo1018** [comment]
centerface.onnx，   this one. 
[centerface.zip](https://github.com/zerollzeng/tiny-tensorrt/files/6331417/centerface.zip)

**Comment by zerollzeng** [comment]
> 你在#27指出： “that's because for caffe you must specify the output name, but for onnx you don't need to specify it.”
> 在使用centerface.onnx 时候，其输出是“537”，“538”，“539”，“540”，
> 
> 1. 如果不指定输出的话，得到的是“537”层的输出；
> 2. 如果指定输出：std::vectorstd::string outputBlobname｛"537","538","539","540"}; 也只会得到“537“层的输出
> 3. 如果单独指定 “540” 其输出个数为：1280个（不是6400）
> 
> 这个问题出现在哪里啊？ 应该怎样改呢

can you describe your problem more clearly? it's a little confusing to me. thx.

**Comment by zerollzeng** [comment]
can you describe how to reproduce the bug?

**Comment by duoduo1018** [comment]
> can you describe how to reproduce the bug?

感谢回复，验证了下， 是onnx模型本身的问题， 换了model模型能正常执行 （虽然得到的检测结果有问题）
