### ISSUE TITLE
Could u give an example for quantize

### ISSUE THREAD

**Issue by liuanhua110** [zerollzeng/tiny-tensorrt#48]
thx for code, it is a cool project

**Comment by zerollzeng** [comment]
do you mean int8 mode?

**Comment by liuanhua110** [comment]
yes thx bro

**Comment by Italy2006** [comment]
> yes thx bro

请问你会写了嘛？

**Comment by zerollzeng** [comment]
I will update the more user-friendly int8 calibration API soon, please be patient :D thx everyone for the feedback

**Comment by vladimirmujagic** [comment]
Any update on int8 python example ?

**Comment by liuanhua110** [comment]
> Any update on int8 python example ?

not yet

**Comment by zerollzeng** [comment]
@liuanhua110 @vladimirmujagic int8 calibration is ready:)
