### ISSUE TITLE
Cmake Error

### ISSUE THREAD

**Issue by chiehpower** [zerollzeng/tiny-tensorrt#5]
Sorry I followed your steps, but cmake step got wrong.
```
$ mkdir build && cd build && cmake .. && make   
                                                                                                                                      
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
ERRORCUDA is needed to check supported architecture values
-- CUDA supported archs: 
ERRORCUDA is needed to check supported architecture values
-- CUDA targeted archs: 
CMake Error at CMakeLists.txt:21 (message):
  None of the provided CUDA architectures ({60;61;70;75}) is supported by
  nvcc, use one or more of:


-- Configuring incomplete, errors occurred!
See also "/home/chieh/github/tiny-tensorrt/build/CMakeFiles/CMakeOutput.log".
```

This is my cmake version below.
```
$nvcc --version  
                                                                                                                                                                            
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89

$cmake --version                                                                                                                                                                             
cmake version 3.15.2
CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

- Ubuntu 18.04
- Python version 3.6
- TensorRT version 7

Is there any idea about this error?

Thanks!

**Comment by zerollzeng** [comment]
which graphic card are you using? tiny-tensorrt has plugin that enable fp16 mode, so it only support CUDA architectures greater than 60

**Comment by chiehpower** [comment]
> which graphic card are you using? tiny-tensorrt has plugin that enable fp16 mode, so it only support CUDA architectures greater than 60

VGA: GTX 1060 NVIDIA

BTW 
I can run many samples which are provided by TensorRT version 6 & 7.

**Comment by zerollzeng** [comment]
emm that's weird, 1060 should support CUDA architectures 61.  did you build it with TensorRT 6? since  TensorRT 7 just release 2 days ago, I haven't upgrade with TensorRT 7 yet.

**Comment by chiehpower** [comment]
Thanks for your reply!
I already removed TensorRT 6. I thought if your project can be accepted by TensorRT 6, it should be accepted by TensorRT 7. (But indeed, there are still some problems in the latest version.) 
Would you mind to consider trying the TensorRT 7 version in the future?

**Comment by zerollzeng** [comment]
oh I find the reason, add find_package(CUDA REQUIRED) to cmakelists.txt before include(cmake/CUDA_utils.cmake) and this issue will be solve.
```cmake
option(BUILD_PYTHON "compile python api" ON)

find_package(CUDA REQUIRED)
# Discover what architectures does nvcc support
include(cmake/CUDA_utils.cmake)
CUDA_find_supported_arch_values(CUDA_supported_archs ${CUDA_known_archs})
message(STATUS "CUDA supported archs: ${CUDA_supported_archs}")
```

**Comment by zerollzeng** [comment]
thanks for your issue, it's a little bug I didn't notice, since I always test tiny-tensorrt with tensorrt-zoo. will commit a fix version

**Comment by chiehpower** [comment]
> oh I find the reason, add find_package(CUDA REQUIRED) to cmakelists.txt before include(cmake/CUDA_utils.cmake) and this issue will be solved.
> 
> ```cmake
> option(BUILD_PYTHON "compile python api" ON)
> 
> find_package(CUDA REQUIRED)
> # Discover what architectures does nvcc support
> include(cmake/CUDA_utils.cmake)
> CUDA_find_supported_arch_values(CUDA_supported_archs ${CUDA_known_archs})
> message(STATUS "CUDA supported archs: ${CUDA_supported_archs}")
> ```

Thanks! It works for me.

**Comment by zerollzeng** [comment]
you are welcome, and thanks for trying tiny-tensorrt and bringing helpful issue!
