### ISSUE TITLE
cmake  in win10 error

### ISSUE THREAD

**Issue by luoww1992** [zerollzeng/tiny-tensorrt#51]
**System environment (please complete the following information):**
 - Device: rtx 2080
 - architectures 7.5
 - OS: win10
 - Env: vs2019 
 - CUDA version: cuda11.0+cudnn8.1
 - TensorRT version: TensorRT 7

**Cmake output**
when i run :cmake .. & make
**Running output**
show error: CMake Error at CMakeLists.txt:83 (message):
  None of the provided CUDA architectures ({60;61;70;75}) is supported
  by nvcc, use one or more of

how to slove?

**Comment by zerollzeng** [comment]
This project does not support windows now, and I can't help you with that since I don't know windows development :)
