### ISSUE TITLE
CopyFromHostToDevice may cause illegal memory access?

### ISSUE THREAD

**Issue by ChenyangLiu** [zerollzeng/tiny-tensorrt#54]
Hi,

I noticed that in
https://github.com/zerollzeng/tiny-tensorrt/blob/f3c5a5ba755963b8a6ba664c4d440476f01f5c8b/Trt.cpp#L106
the code use `mBindingSize[bindIndex]` as copy size. But if the size of input vector is smaller than binding's size, is there any risk that coping from illegal cpu memory?

**Comment by zerollzeng** [comment]
@ChenyangLiu Sorry for the late reply, your suggestion really makes sense, Thank you so much :)
