### ISSUE TITLE
How CuteSamplePlugin works?

### ISSUE THREAD

**Issue by pierrelzw** [zerollzeng/tiny-tensorrt#56]
Think you for your excellent work. I'd like to know how onnx plugin works. 
I used Caffe with pluginFactory to buildEngine. But with onnx, I cannot find any method like `createPlugin`. And there is not code which applies `include <CuteSamplePlugin.h>`. But when I build and run you demo,  CuteSamplePlugin is called. How does it work?

**Comment by zerollzeng** [comment]
https://github.com/zerollzeng/tiny-tensorrt/blob/c5ea8af428854df6523879ef21a6131f09f1b0b6/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp#L209

This is where the magic happens :)

**Comment by pierrelzw** [comment]
Got it! Thanks!

**Comment by pierrelzw** [comment]
> https://github.com/zerollzeng/tiny-tensorrt/blob/c5ea8af428854df6523879ef21a6131f09f1b0b6/plugin/CuteSamplePlugin/CuteSamplePlugin.cpp#L209
> 
> This is where the magic happens :)

Is this a feature of TensorRT7 and 8? Can I use onnx plugin with tensorRT 6?

**Comment by zerollzeng** [comment]
I'm not sure about it, you can refer to API doc.
