### ISSUE TITLE
trttiny/tiny-tensorrt/src/Int8Calibrator.cpp:2:10: fatal error: spdlog/spdlog.h: 没有那个文件或目录

### ISSUE THREAD

**Issue by OutBreak-hui** [zerollzeng/tiny-tensorrt#59]
please descript your problem in **English** if possible. it will to helpful to more people
**Describe the bug**

**To Reproduce**
1. 
2. 

**Screenshots**

**System environment (please complete the following information):**
 - Device:
 - OS:
 - Driver version:
 - CUDA version:
 - TensorRT version:
 - Others:

**Cmake output**

**Running output**

**Comment by zerollzeng** [comment]
try: git submodule init
or
git clone --recurse-submodules https://github.com/zerollzeng/tiny-tensorrt.git

**Comment by OutBreak-hui** [comment]
感谢大佬，可以给个联系方式吗？

**Comment by OutBreak-hui** [comment]
大佬可以加个联系方式吗？运行有疑问想请教一下大佬，我的qq:1039807929

**Comment by OutBreak-hui** [comment]
大佬，生成的.so无法调用，请问大佬方便私聊吗

**Comment by zerollzeng** [comment]
Let's have the discussion here? don't be shy to ask questions :-)

**Comment by OutBreak-hui** [comment]
> 让我们在这里讨论？不要害羞地问问题:-)

import sys
sys.path.append("path/to/where_pytrt.so_located/")
import pytrt
生成的.so，按照上面的操作无法调用

**Comment by zerollzeng** [comment]
错误是怎么样的

**Comment by OutBreak-hui** [comment]
>

**Comment by OutBreak-hui** [comment]
> 错误是正常的

就是显示没有 pytrt这个包
