### ISSUE TITLE
wrong make

### ISSUE THREAD

**Issue by ouyang11111** [zerollzeng/tiny-tensorrt#61]
fatal error: spdlog/spdlog.h: No such file or directory
    2 | #include "spdlog/spdlog.h"
      |          ^~~~~~~~~~~~~~~~~
when i run your demo

**Comment by zerollzeng** [comment]
please clone this repo as readme guided.

**Comment by ouyang11111** [comment]
> please clone this repo as readme guided.

thanks  solved
