### ISSUE TITLE
make后 没有生成pytrt.so呢

### ISSUE THREAD

**Issue by lofyol** [zerollzeng/tiny-tensorrt#67]
please descript your problem in **English** if possible. it will to helpful to more people
**Describe the bug**

**To Reproduce**
1. 
2. 

**Screenshots**

**System environment (please complete the following information):**
 - Device:
 - OS:
 - Driver version:
 - CUDA version:
 - TensorRT version:
 - Others:

**Cmake output**

**Running output**

**Comment by lofyol** [comment]
大佬 有没有详细的使用说明文档

**Comment by zerollzeng** [comment]
https://github.com/zerollzeng/tiny-tensorrt/blob/7dfb55834868b626a660c27249fa324bb184d045/CMakeLists.txt#L3

**Comment by zerollzeng** [comment]
try cmake -DBUILD_PYTHON=ON ..

**Comment by lofyol** [comment]
感谢。
另外就是，执行了trt.CopyFromDeviceToHost(output, index)，output.size( ) 始终等于0是哪里出问题了啊？

**Comment by lofyol** [comment]
void Trt::CopyFromDeviceToHost(std::vector<float>& output, int bindIndex,
                               const cudaStream_t& stream) {
#ifdef DEBUG
    spdlog::info("output size: {}, binding size: {}", output.size()*sizeof(float), mBindingSize[bindIndex]);
#endif
    CUDA_CHECK(cudaMemcpyAsync(output.data(), mBinding[bindIndex],
        output.size()*sizeof(float), cudaMemcpyDeviceToHost, stream));
}

**Comment by lofyol** [comment]
这个函数好像并没有把输出copy到output呀，请问怎么获取forward的结果

**Comment by zerollzeng** [comment]
```
CUDA_CHECK(cudaMemcpyAsync(output.data(), mBinding[bindIndex],
output.size()*sizeof(float), cudaMemcpyDeviceToHost, stream));
```
did the copy, did you call a cudaStreamSynchronize() after this thread? because it's async.

**Comment by lofyol** [comment]
没有执行cudaStreamSynchronize()，我是照着wiki上的C++那几步来的

**Comment by zerollzeng** [comment]
Well if you run the inference in a non-default stream. then you need to call cudaStreamSynchronize() to synchronize the operation.

I would recommend learning some basic CUDA knowledge first, like https://on-demand.gputechconf.com/gtc/2014/presentations/S4158-cuda-streams-best-practices-common-pitfalls.pdf
