### ISSUE TITLE
Support for TRT8.5 and 8.6?

### ISSUE THREAD

**Issue by fujingling** [zerollzeng/tiny-tensorrt#73]
Support for TRT8.5 and 8.6?

**Comment by zerollzeng** [comment]
This project is no longer maintained, but I think compile with TRT 8.5/8.6 should work.

**Comment by zerollzeng** [comment]
Although some new feature is missing.

**Comment by fujingling** [comment]
您好，邮件我已收到！

**Comment by zerollzeng** [comment]
If you just want to use it to build the engine, I would suggest to make use of trtexec/polygraphy.
