### ISSUE TITLE
如何使用对GPU进行推理？

### ISSUE THREAD

**Issue by feizhouxiaozhu** [zerollzeng/tiny-tensorrt#8]
请问坐着，TensorRT或者您的这个项目 如何使用多GPU进行推理。

**Comment by zerollzeng** [comment]
只需要在每个gpu上都build或者load一个引擎即可,复制数据的时候将数据传输到对应的gpu上

**Comment by feizhouxiaozhu** [comment]
请问有示例吗？ 或者推荐个示例也可以啦，谢谢您。

**Comment by zerollzeng** [comment]
单进程的示例你可以参考一下[tensorrt-zoo](https://github.com/zerollzeng/tensorrt-zoo), 里面有一些示例程序,如果你熟悉多线程的话,将他们扩展到多gpu应该不难.

**Comment by feizhouxiaozhu** [comment]
我先学习一下哈，有问题再请教您，谢谢您
