### ISSUE TITLE
onnx 支持 int8 和 fp16吗？

### ISSUE THREAD

**Issue by 121786404** [zerollzeng/tiny-tensorrt#9]

**Comment by zerollzeng** [comment]
支持的, 详情可以看[onnx-tensorrt的文档](https://github.com/onnx/onnx-tensorrt/blob/master/operators.md)

**Comment by 121786404** [comment]
onnx的CreateEngine接口 ，没有看到的参数，
但是caffe的CreateEngine接口有

**Comment by zerollzeng** [comment]
oh我之前开发的时候没有用到这个需求,我下周把它完善一下, 如果你急着用可以参照
https://github.com/zerollzeng/tiny-tensorrt/blob/d3c8a5972be30e9d6d4f43c7391fc2920f6f8f10/Trt.cpp#L294
这里附近的源码,参照着修改
https://github.com/zerollzeng/tiny-tensorrt/blob/d3c8a5972be30e9d6d4f43c7391fc2920f6f8f10/Trt.cpp#L360
这个函数,应该可以满足你的需求

**Comment by zerollzeng** [comment]
只需要把对应的代码复制过去并且修改一下接口应该就可以了,我现在没有测试环境,这几天我会尽快补上,不急的话可以等我更新
